# ArgoCD repository credentials template.
# Apply: kubectl apply -f gitops/argocd/repo-secret.yaml -n argocd
# IMPORTANT: Replace placeholder values before applying.
apiVersion: v1
kind: Secret
metadata:
  name: logclaw-platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: "https://github.com/logclaw/logclaw-platform.git"
  # Option 1 — GitHub App (recommended for production):
  # githubAppID: "YOUR_APP_ID"
  # githubAppInstallationID: "YOUR_INSTALLATION_ID"
  # githubAppPrivateKey: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   ...
  # Option 2 — HTTPS token:
  # username: "x-access-token"
  # password: "ghp_YOUR_TOKEN_HERE"
